### ISSUE TITLE
Fix (email) verification service

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-verifications#85]
Either Zach can fix or can guide me to figuring out where and how to fix over 5-10 minute call

**Comment by zachferland** [comment]
kms.decrypt is hanging with no indication why

**Comment by zachferland** [comment]
Seems to be due to network configuration, ie lambda funcs dont have access to kms endpoint in private subnets, seems like access not through gateway sufficient.... 

Dont remember when this changed, maybe when changing redis configuration, but it did originally work when moving from public network to these priv subnets.

**Comment by zachferland** [comment]
Resolved by getting the right subnet and routing table associations.
